name: CI
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct URL to Decrypted IPA file"
        type: string
        required: true
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get package info
        id: package_info
        run: |
          version=$(grep "PACKAGE_VERSION =" Makefile | cut -d' ' -f3 || grep "Version:" control | cut -d' ' -f2)
          echo "id=$(grep "Package:" control | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rsync build-essential checkinstall git autoconf automake libtool-bin llvm xmlstarlet
          curl -sL https://github.com/libimobiledevice/libplist/releases/download/2.6.0/libplist-2.6.0.tar.bz2 | tar -xj
          cd libplist*
          ./configure && sudo make install && sudo ldconfig

      - name: Download and validate IPA
        run: |
          curl -sLo App.ipa "${{ inputs.ipa_url }}"
          zip -T App.ipa

      - name: Get IPA Info
        id: ipa_info
        run: |
          info=$(unzip -p App.ipa Payload/*.app/Info.plist)
          echo "bundle-id=$(echo "$info" | xmlstarlet sel -t -v "/plist/dict/key[text()='CFBundleIdentifier']/following-sibling::*[1]/text()")" >> $GITHUB_OUTPUT
          echo "version=$(echo "$info" | xmlstarlet sel -t -v "/plist/dict/key[text()='CFBundleShortVersionString']/following-sibling::*[1]/text()")" >> $GITHUB_OUTPUT

      - name: Setup theos
        uses: level3tjg/theos-action@main
        with:
          cache: true
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Setup theos-jailed
        uses: actions/checkout@v4
        with:
          repository: level3tjg/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install theos-jailed
        run: ./theos-jailed/install

      - name: Build packages
        run: |
          # Build rootless deb
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # Build rootful deb
          make clean package FINALPACKAGE=1
          
          # Build IPA
          make package FINALPACKAGE=1 SIDELOADED=1 IPA=App.ipa APP_VERSION=${{ steps.ipa_info.outputs.version }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: packages/*.ipa
          tag_name: v${{ steps.ipa_info.outputs.version }}-${{ steps.package_info.outputs.version }}
