name: CI

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct URL to Decrypted IPA file"
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      ipa_version: ${{ steps.ipa_info.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rsync build-essential checkinstall git autoconf automake libtool-bin llvm xmlstarlet unzip curl

      - name: Cache libplist
        uses: actions/cache@v4
        id: cache-libplist
        with:
          path: ~/libplist-install
          key: libplist-2.6.0

      - name: Build libplist
        if: steps.cache-libplist.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/libimobiledevice/libplist/releases/download/2.6.0/libplist-2.6.0.tar.bz2 | bzip2 -d | tar -x
          cd libplist-2.6.0
          ./configure --prefix=$HOME/libplist-install
          make && make install

      - name: Set libplist env
        run: echo "$HOME/libplist-install/lib" | sudo tee /etc/ld.so.conf.d/libplist.conf && sudo ldconfig

      - name: Download IPA
        run: |
          curl -Lo "${{ github.workspace }}/App.ipa" "${{ inputs.ipa_url }}"
          zip -T "${{ github.workspace }}/App.ipa"

      - name: Get IPA Info
        id: ipa_info
        run: |
          info=$(unzip -p "${{ github.workspace }}/App.ipa" Payload/*.app/Info.plist)
          echo "version=$(echo $info | xmlstarlet sel -t -v "/plist/dict/key[text()='CFBundleShortVersionString']/following-sibling::*[1]/text()")" >> $GITHUB_OUTPUT

      - name: Setup theos
        uses: level3tjg/theos-action@main
        with:
          cache: true
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Checkout theos-jailed
        uses: actions/checkout@v4
        with:
          repository: level3tjg/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install theos-jailed
        run: ./theos-jailed/install

  build-ipa:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build IPA
        run: make package
        env:
          FINALPACKAGE: 1
          SIDELOADED: 1
          IPA: ${{ github.workspace }}/App.ipa
          APP_VERSION: ${{ needs.setup.outputs.ipa_version }}

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App_${{ needs.setup.outputs.ipa_version }}.ipa
          path: packages/*.ipa
